### PR TITLE
contact list fragment added

### PR DESCRIPTION
**Pull request by avirus**
few things as a part of my job for efuzone.com

### CODE REVIEW

**Comment by endymuhardin** [comment]
Your commit also removes Inbox feature, which is not applicable to most users.
Please resubmit only contact management addition

**Comment by avirus** [comment]
you are wrong. this one didn't removes Inbox feature

**Comment by endymuhardin** [comment]
Sorry, I've mistakenly assume this change is related to discussion in google groups also mentioning efuzone :)

I'll review the code again

**Comment by avirus** [comment]
ok, don't you ever thinking about making sms composer as fragment too?

**Comment by lukmanhakim** [comment]
hi, please review your code, i just tested it and i got this error http://pastebin.com/Rb0f6s0e
you didnt import the new classes in your commit, do you ?
i think you miss some lines to commit

**Comment by endymuhardin** [comment]
Please create issue for improvement suggestion (e.g composer as fragment), so we can discuss it separately from this PR :)

**Comment by avirus** [comment]
composer as fragment is not a  improvement suggestion. if you like this feature i can create pull request for this too.

fix for your error is 
    public void showButtonCompose(){
        if (btnComposeMsg!=null) btnComposeMsg.setVisibility(View.VISIBLE);
    }

```
public void hideButtonCompose(){
    if (btnComposeMsg!=null) btnComposeMsg.setVisibility(View.GONE);
}
```

**Comment by endymuhardin** [comment]
Please do create PR for composer fragment. I'll be happy to review it

**Pull request closed without merging**
